services:
  - type: web
    name: financial-dashboard
    env: python
    buildCommand: |
      pip install -r requirements.txt
      # Install frontend dependencies including dev packages for Vue CLI
      npm install --production=false
      npm run build
    startCommand: gunicorn -w 2 wsgi:application
