"""modify portfolio user relation

Revision ID: 93e48ab4b966
Revises: 5cd4428efa0b
Create Date: 2020-07-21 23:26:06.272642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision = '93e48ab4b966'
down_revision = '5cd4428efa0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio', sa.Column('user_id', UUID(as_uuid=True), nullable=False))
    op.create_foreign_key('fk_portfolio_users', 'portfolio', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_users_portfolio', 'users', type_='foreignkey')
    op.drop_column('users', 'portfolio_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('portfolio_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_users_portfolio', 'users', 'portfolio', ['portfolio_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_portfolio_users', 'portfolio', type_='foreignkey')
    op.drop_column('portfolio', 'user_id')
    # ### end Alembic commands ###
