"""uq portfolio

Revision ID: f158a98be596
Revises: b250592af48f
Create Date: 2020-08-16 00:58:44.443164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f158a98be596"
down_revision = "b250592af48f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_portfolio_name_user_id", "portfolio", ["name", "user_id"]
    )
    op.drop_constraint("uq_portfolio_name", "portfolio", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_portfolio_name", "portfolio", ["name"])
    op.drop_constraint("uq_portfolio_name_user_id", "portfolio", type_="unique")
    # ### end Alembic commands ###
