"""add_user_columns

Revision ID: fc1d2203bc12
Revises: 9a1f53dec924
Create Date: 2020-06-24 20:35:45.564194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc1d2203bc12'
down_revision = '9a1f53dec924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('first_name', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=255), nullable=False))
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
